global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nexus-app'
    static_configs:
      - targets: ['host.docker.internal:6000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
